# Generated by Django 3.1 on 2023-09-11 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.subcategory')),
            ],
        ),
    ]
